version: "3"
services:
  build:
    image: ${DOCKER_REGISTRY}milieuinfo/ubuntu-node:14
    command: "npm run build"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy},selenium-hub,tests
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy},selenium-hub,tests
      - NOSELENIUM=1
      - SKIP_WCT_SAUCE_POSTINSTALL_DOWNLOAD=1
      - browserstack_username=${browserstack_username}
      - browserstack_password=${browserstack_password}
    extra_hosts:
      - "repository.milieuinfo.be:${REPOSITORY_FIXED_IP}"
    working_dir: /data
    volumes:
      - ${HOME:-.}/.npmrc:/root/.npmrc:ro
      - ${HOME:-.}/.gitconfig:/root/.gitconfig:ro
      - ${HOME:-.}/.git-credentials:/root/.git-credentials:ro
      - .:/data
  release:
    image: ${DOCKER_REGISTRY}milieuinfo/ubuntu-node:14
    command: "npm run release"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
      - GIT_REPO=${git_repo}
      - RELEASE_VERSION=${release_version}
      - SKIP_WCT_SAUCE_POSTINSTALL_DOWNLOAD=1
    extra_hosts:
      - "repository.milieuinfo.be:${REPOSITORY_FIXED_IP}"
    working_dir: /data
    volumes:
      - ${HOME:-.}/.npmrc:/root/.npmrc:ro
      - ${HOME:-.}/.gitconfig:/root/.gitconfig:ro
      - ${HOME:-.}/.git-credentials:/root/.git-credentials:ro
      - .:/data
