---
version: 2
plan:
  project-key: WEBCO
  key: UIGWEBCOMPONENTS
  name: uig-webcomponents

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Build:
      jobs:
        - Test
  - Release:
      manual: true
      jobs:
        - Release

Test:
  key: BD
  tasks:
    - clean
    - script: |
        #!/bin/bash
        set -e
        export browserstack_username="${bamboo_browserstack_username}"
        export browserstack_password="${bamboo_browserstack_password}"
        docker-compose -f docker-compose.yml run tests --scale selenium-chrome=3 --scale selenium-firefox=3 --exit-code-from tests --force-recreate
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
    - test-parser:
        type: junit
        test-results:
          - results
  requirements:
    - REMOTE_ONLY

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/bin/bash
        set -e
        set -x
        /opt/scripts/git/git-repository-information-restore.sh
        export git_repo="${bamboo_repository_git_repositoryUrl}"
        export release_version="${bamboo.release_version}"
        docker-compose -f docker-compose.yml run release
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: WEBCO-UIGWEBCOMPONENTS

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
