module.exports = {
  VlCustomMap: require('../dist/vl-mapactions.js').CustomMap,
  VlMapWithActions: require('../dist/vl-mapactions.js').MapWithActions,
  VlSnapInteraction: require('../dist/vl-mapactions.js').SnapInteraction,
  VlBoxSelectAction: require('../dist/vl-mapactions.js').BoxSelectAction,
  VlDeleteAction: require('../dist/vl-mapactions.js').DeleteAction,
  VlDrawAction: require('../dist/vl-mapactions.js').DrawAction,
  VlDrawLineAction: require('../dist/vl-mapactions.js').DrawLineAction,
  VlDrawPolygonAction: require('../dist/vl-mapactions.js').DrawPolygonAction,
  VlDrawRectangleAction: require('../dist/vl-mapactions.js').DrawRectangleAction,
  VlHighlightAction: require('../dist/vl-mapactions.js').HighlightAction,
  VlMapAction: require('../dist/vl-mapactions.js').MapAction,
  VlMeasureAction: require('../dist/vl-mapactions.js').MeasureAction,
  VlModifyAction: require('../dist/vl-mapactions.js').ModifyAction,
  VlModifyAndTranslateAction: require('../dist/vl-mapactions.js').ModifyAndTranslateAction,
  VlSelectAction: require('../dist/vl-mapactions.js').SelectAction,
  VlSelectActions: require('../dist/vl-mapactions.js').SelectActions,
  VlShowInfoAction: require('../dist/vl-mapactions.js').ShowInfoAction,
  VlShowInfoSelectAction: require('../dist/vl-mapactions.js').ShowInfoSelectAction,
  VlSplitAction: require('../dist/vl-mapactions.js').SplitAction,
  VlTooltips: require('../dist/vl-mapactions.js').Tooltips,
  VlTranslateAction: require('../dist/vl-mapactions.js').TranslateAction,
};
